id: P2100884D
initial_creation_type: input
source_metadata:
  title: Paksam Wangpo Series
  language: bo
  description: 'Texts by and about Paksam Wangpo (dpag bsam dbang po, 1593–1641),
    the Fifth Drukchen:'
  volume:
    a29cc72a5aef488d97cc32f996971505:
      title: 'Bestower of Supreme Accomplishment: A Torma Offering to Mahākāla'
      parent: Mahākāla
created_at: '2022-03-01T01:09:54.708881'
last_modified_at: '2022-03-01T01:09:54.708884'
statistics:
  total_words: 682
  total_non_words: 91
quality:
  non_words_ratio: 0.13
